language: java
jdk:
  - oraclejdk8
script:
  - |
<<<<<<< HEAD
    mvn apache-rat:check && cd metron-platform && mvn -q integration-test package
=======
    mvn -q integration-test install
>>>>>>> upstream/master
